name: Retrieve Gradle versions
description: Retrieve Gradle versions from services.gradle.org.

inputs:
  min:
    required: false
    description: Minimum Gradle version
  max:
    required: false
    description: Maximum Gradle version
  exclude:
    required: false
    description: Gradle version to exclude

outputs:
  all:
    description: JSON array of all matched Gradle versions
  allAndRC:
    description: JSON array of all matched Gradle versions plus active RC version
  majors:
    description: JSON array of last minor version of every matched Gradle major versions
  majorsAndRC:
    description: JSON array of last minor version of every matched Gradle major versions plus active RC version
  minors:
    description: JSON array of last patch version of every matched Gradle minor versions
  minorsAndRC:
    description: JSON array of last patch version of every matched Gradle minor versions plus active RC version
  activeRC:
    description: Active Release Candidate version

runs:
  using: node16
  main: 'dist/index.js'
