name: Template action
description: Template action description

inputs:
  minVersion:
    required: false
    description: Minimum Gradle version

outputs:


runs:
  using: node12
  main: 'dist/index.js'
