name: Template action
description: Template action description

inputs:
  min:
    required: false
    description: Minimum Gradle version
  max:
    required: false
    description: Maximum Gradle version

outputs:
  all:
    description: JSON array of all matched Gradle versions
  allAndRC:
    description: JSON array of all matched Gradle versions plus active RC version
  lastMinors:
    description: JSON array of last minor matched Gradle versions
  lastMinorsAndRC:
    description: JSON array of last minor matched Gradle versions plus active RC version
  lastPatches:
    description: JSON array of last patch matched Gradle versions
  lastPatchesAndRC:
    description: JSON array of last patch matched Gradle versions plus active RC version

runs:
  using: node12
  main: 'dist/index.js'
